### ISSUE TITLE
Could you please upload the raw dataset, e.g. NIST2017/NIST_Spec.db & NIST2017/NIST_Mol.db?

### ISSUE THREAD

**Issue by mjDelta** [hcji/DeepEI#1]

**Comment by hcji** [comment]
Thanks for your interest for our work. The AC paper is a theoretical introduction paper. We do not have the authorization from NIST to make the data available, neither the trained model (because it is a derivative of the data). So, I cannot give you the db file.

**Comment by hcji** [comment]
You can try with the spectrum in MassBank. Scripts:
https://github.com/hcji/DeepEI/blob/master/Scripts/read_massbank.py

Can download the sdf file of MassBank here:
https://mona.fiehnlab.ucdavis.edu/rest/downloads/retrieve/9e45c27c-d569-4f46-968e-544053fcf44d

**Comment by mjDelta** [comment]
Got it! Thank you!

**Comment by iamjingxian** [comment]
Hi mjDelta, did you manage to get read_massbank.py working? I tried to set it up, but have been experiencing multiple issues. 

let me know if you managed to get read_massbank.py working with massbank's sdf file. 

thanks! 
russ
