### ISSUE TITLE
Usage.ipynb not working

### ISSUE THREAD

**Issue by gchemist** [hcji/DeepEI#2]
Dear hcji,

I have been testing the DeepEI algorithm using the Usage.pynb provided. Unfortunately, the last cell of predicting the fingerprints via the spectra is not working. The pred_fps variable is empty. I am using the mlp_result.txt file available in the DeepEI  package. Do you have an idea of why this could be happening?

Thanks for your help,
Gabe

**Comment by iamjingxian** [comment]
Hi gchemist, did you manage to resolve this issue? I am also having problems (different ones!) with trying to use the codes, and I thought I might experience the same problem you did at some point in time.

**Comment by hcji** [comment]
> Dear hcji,
> 
> I have been testing the DeepEI algorithm using the Usage.pynb provided. Unfortunately, the last cell of predicting the fingerprints via the spectra is not working. The pred_fps variable is empty. I am using the mlp_result.txt file available in the DeepEI package. Do you have an idea of why this could be happening?
> 
> Thanks for your help, Gabe

This is because we did not provide the necessary mass spectrometric data in the repository. see #1 for how to deal with this.
